apiVersion: v1
kind: Namespace
metadata:
  name: wazuh-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh-agent
data:
  authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-wazuh-agent-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  dataLocality: "best-effort"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-agent
  namespace: wazuh-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
      - name: wazuh-agent
        image: matteodalgrande/wazuh-agent-frontend:1.2.21
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
          capabilities:
            add: ["SETGID", "SETUID"]
        volumeMounts:
        - name: wazuh-authd-pass
          mountPath: /var/ossec/etc/authd.pass
          subPath: authd.pass
          readOnly: true
        - name: wazuh-agent-data
          mountPath: /var/ossec
      volumes:
      - name: wazuh-authd-pass
        secret:
          secretName: wazuh-authd-pass
  volumeClaimTemplates:
  - metadata:
      name: wazuh-agent-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn-wazuh-agent-storage"
      resources:
        requests:
          storage: 2Gi
