# path: wazuh-kubernetes/envs/local-env

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../wazuh
patches:
- path: storage-class.yaml
- path: indexer-resources.yaml
- path: wazuh-resources.yaml
- target:
    kind: Service
  path: service-patch.json