# path: wazuh-kubernetes/envs/local-env/

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wazuh-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""